name: pip_install_on_py3_12
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  pip_install_on_py3_12:
    strategy:
      fail-fast: false
      matrix:
        module:
          #- PyWavelets
          #- git+https://github.com/PyWavelets/pywt.git
          #- scikit-image
          - scikit-fuzzy
          - symengine
          - qiskit
          #- git+https://github.com/Qiskit/qiskit.git
          - tensorflow
          #- git+https://github.com/tensorflow/tensorflow.git
          - django django-haystack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - run: pip install ${{ matrix.module }}
    - run: pip uninstall ${{ matrix.module }}
    - run: pip install --upgrade pip
    - run: pip install ${{ matrix.module }}
    
