# A GitHub Action to demonstrate how to run SciPy on Python 3.13 before its release in Oct. 2024

name: scipy_on_py3_13
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  scipy_on_py3_13:
    strategy:
      fail-fast: false
      matrix:
        # Windows see https://docs.scipy.org/doc/scipy-1.13.0/building/index.html#building-from-source
        # os: [macos-latest, ubuntu-latest]  # , windows-latest]
        os: [macos-13, macos-latest]  # , ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: gfortran --version || true
      - run: gfortran -v || true
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
          allow-prereleases: true
      - if: runner.os == 'Linux'  # https://github.com/scipy/scipy/issues/16308#issuecomment-1140477372
        run: |
          sudo apt-get update -qq
          sudo apt-get install --yes libopenblas-dev
      - if: runner.os == 'macOS'
        env:
          # LDFLAGS: "-L/opt/homebrew/opt/openblas/lib"
          # CPPFLAGS: "-I/opt/homebrew/opt/openblas/include"
          # PKG_CONFIG_PATH: "/opt/homebrew/opt/openblas/lib/pkgconfig"
          LDFLAGS: "-L/usr/local/opt/openblas/lib"
          CPPFLAGS: "-I/usr/local/opt/openblas/include"
          PKG_CONFIG_PATH: "/usr/local/opt/openblas/lib/pkgconfig"
        run: |
          brew shellenv
          echo $PATH
          echo $HOMEBREW_PREFIX
          echo $LDFLAGS
          echo $CPPFLAGS
          echo $PKG_CONFIG_PATH
          echo ${{ env.PATH }}
          echo ${{ env.HOMEBREW_PREFIX }}
          brew install openblas
          brew install gfortran
          gfortran --version || true
          gfortran -v || true
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install scipy
          # Some packages that depend on SciPy
          pip install scikit-learn statsmodels
